config/routes.rb
TestApp::Application.routes.draw do

  resources :items
  resources :orders

  get "welcome/index"

  get "pages/home"
  get "pages/contact"
  get "pages/about"
  get "pages/help"

  root :to => 'welcome#index'

  match 'xmlparse' => 'xmlparse#index'
  
end

app/models/item.rb
class Item
  include MongoMapper::Document
  has_many :orders
  
  key :name, String
  
  validates :name, :length => { :maximum => 20, :minimum => 4 }
  
  # many :SellOrders
  # many :BuyOrders

end

app/models/order.rb
class Order
  include MongoMapper::Document
  belongs_to :user

  key :price, Float
  key :vol_remain, Integer
  key :item_id, Integer

  validates_numericality_of  :price, :greater_than => 0 
  validates_numericality_of  :vol_remain, :greater_than => 0
  validates_numericality_of  :item_id, :greater_than => 0 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # GET /items
  # GET /items.json
  def index
    @items = Item.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @items }
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/new
  # GET /items/new.json
  def new
    @item = Item.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(params[:item])

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render json: @item, status: :created, location: @item }
      else
        format.html { render action: "new" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /items/1
  # PUT /items/1.json
  def update
    @item = Item.find(params[:id])

    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @orders }
    end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @order = Order.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/new
  # GET /orders/new.json
  def new
    @order = Order.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/1/edit
  def edit
    @order = Order.find(params[:id])
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(params[:order])

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render json: @order, status: :created, location: @order }
      else
        format.html { render action: "new" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /orders/1
  # PUT /orders/1.json
  def update
    @order = Order.find(params[:id])

    respond_to do |format|
      if @order.update_attributes(params[:order])
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order = Order.find(params[:id])
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
  end

  def contact
    @title = "Contact"
  end

  def about
    @title = "About"
  end

  def help
    @title = "Help"
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @date = DateTime.now.to_s
    @message = "Hello World 2"
  end
end

app/controllers/xmlparse_controller.rb
class XmlparseController < ApplicationController
  def index
    @message = "Hello XML parse"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/xmlparse_helper.rb
module XmlparseHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <!-- <%
=begin
  <div class="field">
    %= f.label :many %<br />
    %= f.text_field :many %
  </div>
  <div class="field">
    %= f.label :many %<br />
    %= f.text_field :many %
  </div>
=end  
  %> -->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<h1>Listing items</h1>

<table>
  <tr>
    <th>Name</th>
<!--     <th>Many</th> -->
<!--     <th>Many</th> -->
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @items.each do |item| %>
  <tr>
    <td><%= item.name %></td>
<!--    <td>%= item.many %</td>-->
<!--    <td>%= item.many %</td>-->
    <td><%= link_to 'Show', item %></td>
    <td><%= link_to 'Edit', edit_item_path(item) %></td>
    <td><%= link_to 'Destroy', item, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @item.name %>
</p>

<!-- <%
=begin
<p>
  <b>Many:</b>
  %= @item.many %
</p>

<p>
  <b>Many:</b>
 <%= @item.many %
</p>
=end
%> -->

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/pages.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestApp | <%= @title %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<div><a href="/">Back to Index</a></div>

</body>
</html>

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :vol_remain %><br />
    <%= f.number_field :vol_remain %>
  </div>
  <div class="field">
    <%= f.label :item_id %><br />
    <%= f.number_field :item_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<h1>Listing orders</h1>

<table>
  <tr>
    <th>Price</th>
    <th>Vol remain</th>
    <th>Item</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @orders.each do |order| %>
  <tr>
    <td><%= order.price %></td>
    <td><%= order.vol_remain %></td>
    <td><%= order.item_id %></td>
    <td><%= link_to 'Show', order %></td>
    <td><%= link_to 'Edit', edit_order_path(order) %></td>
    <td><%= link_to 'Destroy', order, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Price:</b>
  <%= @order.price %>
</p>

<p>
  <b>Vol remain:</b>
  <%= @order.vol_remain %>
</p>

<p>
  <b>Item:</b>
  <%= @order.item_id %>
</p>


<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/pages/about.html.erb
<h1><%= @title %></h1>
<p>
	This is the home page for the <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
	sample application.
</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/help.html.erb
<h1><%= @title %></h1>
<p>
	This is the home page for the <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
	sample application.
</p>

app/views/pages/home.html.erb
<h1><%= @title %></h1>
<p>
	This is the home page for the <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
	sample application.
</p>

app/views/welcome/index.html.erb
<h1>Welcome to the Rails Installer Demo !!!</h1>
<h1>v.0 <%= @date %> :: <%= @message %></h1>
<p>
	Find me in app/views/welcome/index.html.erb
</p>
<div id="include-in-html">
	<h2>Mine</h2>
	<ul>
		<li>
			<a href="items">Items</l>
		</li>
		<li>
			<a href="orders">Orders</l>
		</li>
		<li>
			<a href="pages/about">About</l>
		</li>
		<li>
			<a href="pages/contact">Contact</l>
		</li>
		<li>
			<a href="pages/home">Home</l>
		</li>
		<li>
			<a href="pages/help">Help</l>
		</li>
	</ul>
	<h2>Enumeration</h2>
	<ul>
		<%(1..10).each do|i|%>
		<li>
			number <%= i%>
		</li>
		<%end%>
	</ul>
	<h2>Environment variables</h2>
	<table>
		<%ENV.keys.sort.each do |key|%>
		<tr>
			<th><%= key%></th><td><%= ENV[key]%></td>
		</tr>
		<%end%>
	</table>
</div>

app/views/xmlparse/index.html.erb
<div id="message">
<%= @message %>
</div>